### PR TITLE
fix: tasks panel empty on win machines

### LINKED ISSUE #991: Task panel doesn't show any tasks (works w/3.26 but not 3.27)
**Describe the bug**
No tasks appear in the pane when VSCode starts.  Downgrading manually to 3.26 fixes the issue.

**To Reproduce**
1. Put tasks in deno.jsonc at project root.
2. Open VSCode w/deno extension 3.27

**Expected behavior**
Tasks appear in tasks pane.

**Versions**
vscode: 1.84.2 deno: 1.38.1 extension: 3.27

### PR DESCRIPTION
**Pull request by Nedgeva**
Fixes #991

### CODE REVIEW

File: client/src/tasks_sidebar.ts [hunk 1]
```diff
@@ -162,9 +162,13 @@ class DenoTaskProvider implements TaskProvider {
           if (!sourceUri) {
             continue;
           }
-          const workspaceFolder = (workspace.workspaceFolders ?? []).find((
-            f,
-          ) => sourceUri.startsWith(f.uri.toString()));
+          const workspaceFolder = (workspace.workspaceFolders ?? []).find((f) =>
+            // NOTE: skipEncoding in Uri.toString(), read more at https://github.com/microsoft/vscode/commit/65cb3397673b922c1b6759d145a3a183feb3ee5d
+            sourceUri
+              .toString(true)
```
Comment (nayeemrmn) [inline client/src/tasks_sidebar.ts:168]: This doesn't take an argument apparently

Comment (Nedgeva) [reply client/src/tasks_sidebar.ts]: Yeah, sorry, Totally forgot that `sourceUri` is just string actually.

**Review by nayeemrmn — APPROVED** [review]
LGTM, thanks!
